name: CI - hello

on:
  push:
  pull_request:

# Needed so the workflow can push to GHCR
permissions:
  contents: read
  packages: write

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say hi from the runner
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
          uname -a
          date
          ls -la

  test-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run pytest
        env:
          PYTHONPATH: .
        run: python -m pytest -q --maxfail=1 --disable-warnings
      - name: Upload pytest cache (optional)
        uses: actions/upload-artifact@v4
        with:
          name: py-test-logs
          path: .pytest_cache
          if-no-files-found: ignore

  docker:
    # Only build if tests passed
    needs: test-py
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository_owner }}/ci-cd-basics
      TAG1: latest
      TAG2: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG1 }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG2 }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
