name: CI - hello

on:
  push:
  pull_request:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Say hi from the runner
        run: |
          echo "Repo: $GITHUB_REPOSITORY"
          echo "Ref: $GITHUB_REF"
          echo "SHA: $GITHUB_SHA"
          uname -a
          date
          ls -la

  test-py:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - name: Run pytest
        env:
          PYTHONPATH: .
        run: python -m pytest -q --maxfail=1 --disable-warnings
      - name: Upload pytest cache (optional)
        uses: actions/upload-artifact@v4
        with:
          name: py-test-logs
          path: .pytest_cache
          if-no-files-found: ignore

